//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENCYSETTING
    {
        public int ID { get; set; }
        public string AGENCY { get; set; }
        public Nullable<int> FEATURECOUNTLIMIT { get; set; }
    }
}
