//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENCY
    {
        public int AGENCYID { get; set; }
        public string AGENCYNAME { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> CREATEDTIME { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDTIME { get; set; }
        public string UPDATEDBY { get; set; }
    }
}
