//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENCYWIDGET
    {
        public int ID { get; set; }
        public string CONFIGURATIONKEY { get; set; }
        public string WIDGETID { get; set; }
        public string AGENCYNAME { get; set; }
    }
}
