//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURATIONLAYER
    {
        public int LAYERID { get; set; }
        public string LAYERKEY { get; set; }
        public string LAYERCODE { get; set; }
        public string LAYERNAME { get; set; }
        public string LAYERICON { get; set; }
        public string SERVICEKEY { get; set; }
        public string PARENTLAYERCODE { get; set; }
        public string SRS { get; set; }
        public string LAYERTYPE { get; set; }
        public string LEGENDDATA { get; set; }
        public string LEGENDTYPE { get; set; }
        public string GID { get; set; }
        public string URL { get; set; }
    }
}
