//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURATIONLAYERFIELD
    {
        public int FIELDID { get; set; }
        public Nullable<int> LAYERID { get; set; }
        public string LAYERKEY { get; set; }
        public string FIELDCODE { get; set; }
        public string FIELDNAME { get; set; }
        public string FIELDIDFIELD { get; set; }
        public string FIELDTYPE { get; set; }
        public string ALIAS { get; set; }
        public string SQLTYPE { get; set; }
        public string NULLABLE { get; set; }
        public string EDITABLE { get; set; }
        public string DOMAINNAME { get; set; }
        public string DOMAINTYPE { get; set; }
        public string DEFAULTVALUE { get; set; }
    }
}
