//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURATIONWIDGET
    {
        public int ID { get; set; }
        public string CONFIGURATIONKEY { get; set; }
        public string WIDGETID { get; set; }
        public string WIDGETNAME { get; set; }
        public string WIDGETLABEL { get; set; }
        public string WIDGETURI { get; set; }
        public string WIDGETCUSTOMIZE { get; set; }
        public string POSITIONLEFT { get; set; }
        public string POSITIONTOP { get; set; }
        public string POSITIONRIGHT { get; set; }
        public string POSITIONBOTTOM { get; set; }
        public string POSITIONWIDTH { get; set; }
        public string POSITIONHEIGHT { get; set; }
        public string POSITIONMARGINRIGHT { get; set; }
        public string POSITIONFIXED { get; set; }
        public string POSITIONOFFSET { get; set; }
        public string PANELURI { get; set; }
        public string CONFIG { get; set; }
    }
}
