//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURATION
    {
        public int ID { get; set; }
        public string CONFIGURATIONKEY { get; set; }
        public string AGENCY { get; set; }
        public string HTTPPROXY { get; set; }
        public string ITEMID { get; set; }
        public string URL { get; set; }
        public string CLIENID { get; set; }
        public string MAPSERVICENAME { get; set; }
        public string INTERGRATIONNAME { get; set; }
        public string MAPSERVICETHUMBNAIL { get; set; }
        public string AAGISSERVICEID { get; set; }
        public string APPSERVERURL { get; set; }
        public string AAUSERNAME { get; set; }
        public string AAPASSWORD { get; set; }
        public string ISDEFAULT { get; set; }
        public string SERVICEAREADRIVETIME { get; set; }
        public string POSITIONLEFT { get; set; }
        public string POSITIONTOP { get; set; }
        public string POSITIONRIGHT { get; set; }
        public string POSITIONBOTTOM { get; set; }
        public string POSITIONWIDTH { get; set; }
        public string POSITIONHEIGHT { get; set; }
        public string POSITIONMARGINRIGHT { get; set; }
        public string THEMENAME { get; set; }
        public string THEMESTYLES { get; set; }
        public string PRODUCT { get; set; }
        public Nullable<int> ENABLEPERSISTMAPSTATUS { get; set; }
        public string AAMAPPINGMAPPROFILEKEY { get; set; }
        public string AAMAPPINGSERVICEKEY { get; set; }
        public string AAMAPPINGLAYERKEY { get; set; }
    }
}
