//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURATIONDYNAMICTHEME
    {
        public int ID { get; set; }
        public string CONFIGURATIONKEY { get; set; }
        public string DYNAMICTHEMEID { get; set; }
        public string STROKERCOLOR { get; set; }
        public Nullable<int> STROKERTHICKNESS { get; set; }
        public string FILLCOLOR { get; set; }
        public Nullable<int> INDEXNUM { get; set; }
        public Nullable<int> VISIBILITY { get; set; }
        public string DYNAMICTHEMENAME { get; set; }
        public string DYNAMICTHEMEGROUPNAME { get; set; }
    }
}
