//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLOBALSETTING
    {
        public int ID { get; set; }
        public int LOGLEVEL { get; set; }
        public int LOGPERIOD { get; set; }
        public Nullable<System.DateTime> UPDATEDTIME { get; set; }
        public string UPDATEDBY { get; set; }
        public string DISABLESHA1 { get; set; }
    }
}
