//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int ID { get; set; }
        public string TRACEID { get; set; }
        public string LOGLEVEL { get; set; }
        public string USERNAME { get; set; }
        public string AGENCY { get; set; }
        public string APP { get; set; }
        public string APPVER { get; set; }
        public string ENVNAME { get; set; }
        public string MESSAGE { get; set; }
        public string DETAIL { get; set; }
        public string DETAILBLOBURI { get; set; }
        public Nullable<int> DETAILSIZE { get; set; }
        public string METHODNAME { get; set; }
        public Nullable<int> METHODEXECUTETIME { get; set; }
        public Nullable<int> METHODINSIZE { get; set; }
        public Nullable<int> METHODOUTSIZE { get; set; }
        public string REQUESTFROM { get; set; }
        public string REQUESTTO { get; set; }
        public string REQUESTTOSERVER { get; set; }
        public Nullable<int> LOGSORDER { get; set; }
        public string PRODUCT { get; set; }
        public string SERVICEID { get; set; }
        public string INTEGRATIONNAME { get; set; }
        public System.DateTime DATECREATED { get; set; }
    }
}
