//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAPPROFILESERVICE
    {
        public int SERVICEID { get; set; }
        public string PROFILEKEY { get; set; }
        public string SERVICEKEY { get; set; }
        public string SERVICETYPE { get; set; }
        public string MAPSERVICEID { get; set; }
        public string MAPSERVICENAME { get; set; }
        public string MAPSERVICEURL { get; set; }
        public string MAPSERVICETHUMBNAIL { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string GISPROVIDER { get; set; }
        public string GISSERVER { get; set; }
        public string SERVERPORT { get; set; }
        public string GISINSTANCE { get; set; }
        public string SERVERISSSL { get; set; }
        public string INITIALEXTENT { get; set; }
        public string FULLEXTENT { get; set; }
        public string ISDEFAULT { get; set; }
        public string SUPPORTSDYNAMICLAYERS { get; set; }
        public string SINGLEFUSEDMAPCACHE { get; set; }
        public string SPATIALREFERENCE { get; set; }
        public string MINSCALE { get; set; }
        public string MAXSCALE { get; set; }
        public string UNITS { get; set; }
        public string TILEINFO { get; set; }
        public string WMSSERVER { get; set; }
        public string WFSSERVER { get; set; }
        public string SUPPORTEDEXTENSIONS { get; set; }
        public Nullable<int> ORDERNUMBER { get; set; }
    }
}
