//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPGRADE_SCRIPTS
    {
        public int SCRIPT_SEQ { get; set; }
        public string SCRIPT_NAME { get; set; }
        public string RELEASE_VERSION { get; set; }
        public string SCRIPT_APPLIED { get; set; }
        public System.DateTime REC_DATE { get; set; }
        public string REC_FUL_NAM { get; set; }
        public string REC_STATUS { get; set; }
    }
}
