//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERGROUP
    {
        public string USERGROUPID { get; set; }
        public string CONFIGURATIONKEY { get; set; }
        public string MAPPROFILEKEY { get; set; }
        public string USERGROUPNAME { get; set; }
        public string USERGROUPDESCRIPTION { get; set; }
        public string WIDGETLAYOUT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDTIME { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDTIME { get; set; }
    }
}
