//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERPROFILE
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string AGENCY { get; set; }
        public int ROLE { get; set; }
        public int STATUS { get; set; }
        public Nullable<System.DateTime> CREATEDTIME { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDTIME { get; set; }
        public string UPDATEDBY { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string LASTNAME { get; set; }
        public string DEPARTMENT { get; set; }
        public string MOBILEPHONE { get; set; }
        public string OFFICEPHONE { get; set; }
        public string SECURITYQUESTION { get; set; }
        public string SECURITYANSWER { get; set; }
        public string SHAPASSWORD { get; set; }
        public string SALT { get; set; }
    }
}
