//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERGROUPLAYERSETTING
    {
        public int SETTINGID { get; set; }
        public string USERGROUPID { get; set; }
        public string SERVICEKEY { get; set; }
        public string ISAVAIABLE { get; set; }
        public string ISVISABLE { get; set; }
        public string ISEDITABLE { get; set; }
        public string EDITABLEUSERS { get; set; }
        public string USERGROUPDESCRIPTION { get; set; }
        public string LAYERCODE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDTIME { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDTIME { get; set; }
        public Nullable<int> DYNAMICTHEMEID { get; set; }
        public string DYNAMICTHEMEGROUP { get; set; }
    }
}
