//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERGROUPDETAIL
    {
        public int DETAILID { get; set; }
        public string USERGROUPID { get; set; }
        public Nullable<int> AAGROUPID { get; set; }
        public string AAGROUPNAME { get; set; }
        public string AAGROUPDESCRIPTION { get; set; }
        public string AAMODULENAME { get; set; }
        public string AAMODULEKEY { get; set; }
        public string AASTATUSTITLE { get; set; }
        public string AASTATUSVALUE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDTIME { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDTIME { get; set; }
    }
}
